"""Models package."""

from models.auth import (
    APIKey,
    APIKeyCreate,
    APIKeyResponse,
    LoginRequest,
    LoginResponse,
    PasswordChangeRequest,
    PasswordResetConfirm,
    PasswordResetRequest,
    PermissionScope,
    SessionRevoke,
    TokenRefreshRequest,
    TokenRefreshResponse,
    User,
    UserCreate,
    UserRole,
    UserSession,
    UserUpdate,
)
from models.business import (
    CRMDeal,
    CustomerLifetimeValue,
    CustomerSegment,
    DealPriority,
    DealStage,
    DealUpdate,
    OrderItem,
    OrderQuote,
    OrderQuoteUpdate,
    OrderStatus,
    PaymentIntent,
    PaymentMethod,
    PaymentStatus,
)
from models.customer import (
    Customer,
    CustomerType,
    DesignPreferences,
    Measurements,
    SessionState,
)
from models.fabric import (
    FabricChunk,
    FabricColor,
    FabricData,
    FabricPattern,
    FabricRecommendation,
    FabricSearchCriteria,
    GeneratedOutfit,
    OutfitSpec,
    Season,
    StockStatus,
)
from models.graph_state import HenkGraphState, create_initial_graph_state
from models.handoff import (
    CustomerCommitment,
    DesignHenkToLaserHenkPayload,
    GarmentType,
    HandoffValidator,
    Henk1ToDesignHenkPayload,
    InnerLiningType,
    JacketForm,
    LaserHenkToHITLPayload,
    OccasionType,
    ReversType,
    ShoulderProcessing,
    StyleType,
)
from models.tools import (
    CRMLeadCreate,
    CRMLeadResponse,
    CRMLeadUpdate,
    DALLEImageRequest,
    DALLEImageResponse,
    RAGQuery,
    RAGResult,
    SAIAMeasurementRequest,
    SAIAMeasurementResponse,
)

__all__ = [
    # Auth models
    "User",
    "UserRole",
    "UserCreate",
    "UserUpdate",
    "PermissionScope",
    "LoginRequest",
    "LoginResponse",
    "TokenRefreshRequest",
    "TokenRefreshResponse",
    "PasswordChangeRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "UserSession",
    "SessionRevoke",
    "APIKey",
    "APIKeyCreate",
    "APIKeyResponse",
    # Business models
    "CRMDeal",
    "DealStage",
    "DealPriority",
    "DealUpdate",
    "OrderQuote",
    "OrderItem",
    "OrderStatus",
    "OrderQuoteUpdate",
    "PaymentIntent",
    "PaymentMethod",
    "PaymentStatus",
    "CustomerSegment",
    "CustomerLifetimeValue",
    # Customer models
    "Customer",
    "CustomerType",
    "Measurements",
    "DesignPreferences",
    "SessionState",
    # Graph state
    "HenkGraphState",
    "create_initial_graph_state",
    # Fabric models
    "FabricData",
    "FabricSearchCriteria",
    "FabricRecommendation",
    "FabricChunk",
    "OutfitSpec",
    "GeneratedOutfit",
    "Season",
    "FabricPattern",
    "FabricColor",
    "StockStatus",
    # Handoff models
    "Henk1ToDesignHenkPayload",
    "DesignHenkToLaserHenkPayload",
    "LaserHenkToHITLPayload",
    "HandoffValidator",
    # Handoff enums
    "StyleType",
    "OccasionType",
    "GarmentType",
    "JacketForm",
    "ShoulderProcessing",
    "ReversType",
    "InnerLiningType",
    "CustomerCommitment",
    # Tool models
    "RAGQuery",
    "RAGResult",
    "CRMLeadCreate",
    "CRMLeadUpdate",
    "CRMLeadResponse",
    "DALLEImageRequest",
    "DALLEImageResponse",
    "SAIAMeasurementRequest",
    "SAIAMeasurementResponse",
]
